name: Publicar NexusBus NuGet

on:
  push:
    branches: [ "master" ]
    paths:
      - 'NexusBus/**'  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x 

    - name: Restore dependencies
      run: dotnet restore NexusBus

    - name: Pack
      run: |
        dotnet pack NexusBus/NexusBus.csproj --no-restore -c Release -o out \
        -p:PackageVersion=1.0.${{ github.run_number }}
        
    - name: Push to NuGet
      run: dotnet nuget push "**/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
